<?php

use Statikbe\FilamentVoight\Enums\DependencyKind;
use Statikbe\FilamentVoight\Enums\PackageType;
use Statikbe\FilamentVoight\Enums\SyncWarning;
use Statikbe\FilamentVoight\Parsers\UnsupportedLockfileException;
use Statikbe\FilamentVoight\Parsers\YarnLockParser;

function parseYarnFixture(bool $withManifest = true): array
{
    return byKey((new YarnLockParser)->parse(
        lockfileFixture('yarn/yarn.lock'),
        $withManifest ? lockfileFixture('yarn/package.json') : null,
    ));
}

it('parses every block as a node keyed by its first descriptor', function () {
    $packages = parseYarnFixture();

    expect(array_keys($packages))->toEqualCanonicalizing([
        '@vue/runtime-core@3.4.0', '@vue/shared@3.4.0', 'debug@2.6.9', 'debug@^4.3.4', 'esbuild@^0.19.3',
        'express@^4.18.2', 'fsevents@~2.3.3', 'ms@2.0.0', 'ms@2.1.2', 'send@0.18.0', 'vite@^5.0.0', 'vue@^3.4.0',
    ])
        ->and($packages['@vue/shared@3.4.0']['name'])->toBe('@vue/shared')
        ->and($packages['debug@^4.3.4']['name'])->toBe('debug')
        ->and($packages['debug@^4.3.4']['version'])->toBe('4.3.4')
        ->and($packages['vue@^3.4.0']['type'])->toBe(PackageType::Npm);
});

it('resolves dependencies through every descriptor of a block, keeping the range', function () {
    $send = parseYarnFixture()['send@0.18.0'];

    expect($send['dependencies'])->toBe([
        ['key' => 'debug@2.6.9', 'constraint' => '2.6.9', 'kind' => DependencyKind::Dependency],
        ['key' => 'ms@2.1.2', 'constraint' => '^2.1.1', 'kind' => DependencyKind::Dependency],
    ]);
});

it('resolves scoped dependencies and marks optional dependencies', function () {
    $packages = parseYarnFixture();

    expect(dependencyKeys($packages['vue@^3.4.0']))->toBe(['@vue/runtime-core@3.4.0', '@vue/shared@3.4.0'])
        ->and(collect($packages['vite@^5.0.0']['dependencies'])->firstWhere('key', 'fsevents@~2.3.3')['kind'])
        ->toBe(DependencyKind::Optional);
});

it('marks the blocks package.json declares as direct', function () {
    $direct = collect(parseYarnFixture())->where('is_direct', true)->keys()->sort()->values()->all();

    expect($direct)->toBe(['express@^4.18.2', 'vite@^5.0.0', 'vue@^3.4.0']);
});

it('marks dev roots and what only they reach as dev', function () {
    $dev = collect(parseYarnFixture())->where('is_dev', true)->keys()->sort()->values()->all();

    // ms@2.1.2 is also reached by send (production) through ms@^2.1.1, so it is not dev.
    expect($dev)->toBe(['debug@^4.3.4', 'esbuild@^0.19.3', 'fsevents@~2.3.3', 'vite@^5.0.0']);
});

it('falls back to unrequired blocks as direct production packages without package.json', function () {
    $packages = collect(parseYarnFixture(withManifest: false));

    expect($packages->where('is_direct', true)->keys()->sort()->values()->all())
        ->toBe(['express@^4.18.2', 'vite@^5.0.0', 'vue@^3.4.0'])
        ->and($packages->where('is_dev', true))->toBeEmpty();
});

it('handles multiple version ranges for same package', function () {
    $content = <<<'YARN'
# yarn lockfile v1

"lodash@^4.17.0", "lodash@^4.17.21":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
YARN;

    $parser = new YarnLockParser;
    $packages = $parser->parse($content);

    expect($packages)->toHaveCount(1)
        ->and($packages[0]['name'])->toBe('lodash')
        ->and($packages[0]['version'])->toBe('4.17.21');
});

it('returns empty array for empty content', function () {
    $parser = new YarnLockParser;
    $packages = $parser->parse('');

    expect($packages)->toBeEmpty();
});

it('returns empty array for comment-only content', function () {
    $parser = new YarnLockParser;
    $packages = $parser->parse("# yarn lockfile v1\n");

    expect($packages)->toBeEmpty();
});

it('parses CRLF line endings identically to LF (Windows regression)', function () {
    $lf = <<<'YARN'
# yarn lockfile v1

"lodash@^4.17.0":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
YARN;

    $crlf = str_replace("\n", "\r\n", $lf);

    $parser = new YarnLockParser;
    $packages = $parser->parse($crlf);

    expect($packages)->toHaveCount(1);
    expect($packages[0]['name'])->toBe('lodash')
        ->and($packages[0]['version'])->toBe('4.17.21')
        ->and($packages[0]['type'])->toBe(PackageType::Npm);
});

it('rejects a yarn berry lockfile as unsupported', function () {
    $berryLock = <<<'YAML'
# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
YAML;

    expect(fn () => (new YarnLockParser)->parse($berryLock))
        ->toThrow(fn (UnsupportedLockfileException $e) => expect($e->warning)->toBe(SyncWarning::YarnBerryUnsupported));
});
